language: node_js
node_js:
  - "node"
install:
  - npm i -g npm@5.8.0
  - npm ci
script:
  - npm run test
  - npm install codecov -g
after_success:
  - codecov
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"